"""users table added

Revision ID: 24cf834851cb
Revises: 9b412a6ca0c3
Create Date: 2026-07-01 14:52:24.766889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
                                                                

# revision identifiers, used by Alembic.
revision: str = '24cf834851cb'
down_revision: Union[str, Sequence[str], None] = '9b412a6ca0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
                                                                

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
